### ISSUE TITLE
Configure failure with bmake 20160315

### ISSUE THREAD

**Issue by DAP-DarkneSS** [cheusov/mk-configure#13]
Distro: all openSUSE realeses
Arch: all tested
Course: bmake 20160307 → 20160315
Error:
[   73s] + bmake all
[   73s] sh: line 0: test: -ge: unary operator expected
[   73s] bmake[1]: "/home/abuild/rpmbuild/BUILD/mk-configure-0.29.1/mk/mkc_imp.preinit.mk" line 19: "bmake-20110606 or newer is required"
[   73s] *** Error code 1
[   73s] 
[   73s] Stop.
[   73s] bmake: stopped in /home/abuild/rpmbuild/BUILD/mk-configure-0.29.1

**Comment by DAP-DarkneSS** [comment]
The same with 20160512.

**Comment by cheusov** [comment]
Actually, this a bug in bmake. Some time ago its MAKE_VERSION variable was broken.
Try to apply the following patch to it.
[bmake-patch1.patch.txt](https://github.com/cheusov/mk-configure/files/284833/bmake-patch1.patch.txt)

**Comment by DAP-DarkneSS** [comment]
Thanks but patch should be reversed :)

**Comment by cheusov** [comment]
Does this solve the problem with mk-configure?

**Comment by DAP-DarkneSS** [comment]
Yes, it does:  
https://build.opensuse.org/package/show/home:DarkSS/mk-configure
