### ISSUE TITLE
mk-configure and bmake MAKEOBJDIR 

### ISSUE THREAD

**Issue by grylem** [cheusov/mk-configure#16]
Здравствуйте, Алексей.
Если в bashrc выставлены:
export MAKEOBJDIR=`pwd`/obj
export WITH_AUTO_OBJ=1
то при выполнении bmake all

all ===> features
cp mkc_imp.f_SLIST.mk mkc_imp.f_SIMPLEQ.mk
cp: mkc_imp.f_SLIST.mk: No such file or directory
*** Error code 1
Удачи.

**Comment by cheusov** [comment]
mkcmake должен собираться без MAKEOBJDIR и MAKEOBJDIRPREFIX. Причина в тестах, которые на это не рассчитаны.
