### ISSUE TITLE
MKC_CHECK_SIZEOF works incorrectly

### ISSUE THREAD

**Issue by niclasr** [cheusov/mk-configure#17]
When using MKC_CHECK_SIZEOF with size_t:sys/types.h the resulting define becomes
-DSIZEOF_SIZE_T_SYS/TYPES_H when it should be -DSIZEOF_SIZE_T_SYS_TYPES_H . 
This leads to division in the preprocessor so it can't be used.

**Comment by cheusov** [comment]
Thank you for your patch!
