### ISSUE TITLE
mk-configure requires nawk or gawk

### ISSUE THREAD

**Issue by niclasr** [cheusov/mk-configure#21]
While running mk-configure on [omniosce](https://omniosce.org/) mkc_check_compiler fails with a non-zero exit staus. The fix for it was to put /usr/xpg4/bin first in PATH. According to the docs /usr/xpg4/bin/awk is the same as nawk. It would be nice if mk-configure would use nawk or gawk out of the box on systems that have an awk that is incompatible with mk-configure.

**Comment by cheusov** [comment]
Unfortunately I've lost my shell account on Solaris-11 and 10 and therefore cannot reproduce the problem. However I definitely tested it on both these Solarises. So, I believe mk-configure should work perfectly provided that /usr/xpg4/bin is in the path before /usr/bin.

**Comment by niclasr** [comment]
Hi, yes doing like that works. Thanks for merging the pull request.
