### ISSUE TITLE
env: mkc_check_custom: No such file or directory

### ISSUE THREAD

**Issue by ryandesign** [cheusov/mk-configure#25]
I am trying to install mk-configure (0.37.0) for the first time (on macOS 10.15.7) hoping to add it to MacPorts. It doesn't get very far:

```
$ sudo -u macports bmake configure
Password:
==================================================
configure ===> scripts
==================================================
configure ===> builtins
==================================================
configure ===> examples/helpers
==================================================
configure ===> mk
env: mkc_check_custom: No such file or directory
```

If I try making `mkc_check_custom` first, that doesn't get far either:

```
$ sudo -u macports bmake mkc_check_custom
==================================================
all ===> tests/mkc_check_custom
env: mkc_check_compiler: No such file or directory
bmake[2]: "mk/mkc_imp.platform.sys.mk" line 102: warning: "env CC=cc CXX=c++ CPPFLAGS=\  CFLAGS= LDFLAGS= LDADD= MKC_CACHEDIR=tests/mkc_check_custom MKC_DELETE_TMPFILES= MKC_SHOW_CACHED= MKC_NOCACHE= MKC_VERBOSE=1 mkc_check_compiler " returned non-zero status
env: mkc_check_compiler: No such file or directory
bmake[2]: "mk/mkc_imp.platform.sys.mk" line 102: warning: "env CC=cc CXX=c++ CPPFLAGS=\  CFLAGS= LDFLAGS= LDADD= MKC_CACHEDIR=tests/mkc_check_custom MKC_DELETE_TMPFILES= MKC_SHOW_CACHED= MKC_NOCACHE= MKC_VERBOSE=1 mkc_check_compiler -x" returned non-zero status
```

If I just run `bmake` (not `bmake configure`) it doesn't error. But doc/INSTALL.md says I should run `bmake configure`.

**Comment by cheusov** [comment]
I can reproduce the problem. Use just "bmake" for build and "bmake install" for installation.
It would be better to run these commands in clean directory. So, make sure you run "bmake -k cleandir" first.
Also note, that mkcmake is packaged for brew, so you can grab something useful for mac-ports from there.

Thanks for pointing out!

**Comment by cheusov** [comment]
Please follow instructions from doc/INSTALL.md file for installation.
