### ISSUE TITLE
Can't find library in /usr/local/lib/

### ISSUE THREAD

**Issue by inferrna** [cheusov/mk-configure#26]
Trying to build dictd got
`ERROR: cannot find function lst_create:maa`
which is actually present in  `/usr/local/lib/`
```shell
ls -alh /usr/local/lib/libmaa.*
-rw-r--r-- 1 root root 186K Jan  7 17:50 /usr/local/lib/libmaa.a
lrwxrwxrwx 1 root root   13 Jan  7 17:50 /usr/local/lib/libmaa.so -> libmaa.so.4.0
lrwxrwxrwx 1 root root   13 Jan  7 17:50 /usr/local/lib/libmaa.so.4 -> libmaa.so.4.0
-rw-r--r-- 1 root root  96K Jan  7 17:50 /usr/local/lib/libmaa.so.4.0
```

adding `/usr/local/lib` to `LD_LIBRARY_PATH` doesn't help.

**Comment by cheusov** [comment]
LD_LIBRARY_PATH is unrelated for compiling and linking. This variable is for run-time only.
For building dictd you have to do something like the following

$ export CPPFLAGS=-I/usr/local/include
$ export LDFLAGS=-L/usr/local/lib
$ mkcmake

or the following if you want to also include /usr/local/lib to runtime paths

$ export CPPFLAGS=-I/usr/local/include
$ export LDFLAGS='-L/usr/local/lib -Wl,-rpath,/usr/local/lib'
$ mkcmake

Actually, CPPFLAGS and LDFLAGS are standard environment variables for building software on UNIX systems.
