### ISSUE TITLE
Distros are using github tags to track releases

### ISSUE THREAD

**Issue by wdlkmpx** [cheusov/mk-configure#28]
At least I see Arch and Alpine are using this:
https://github.com/cheusov/mk-configure/tags

Apparently all distros use the github tags... 0.37.0
https://repology.org/project/mk-configure/versions

It's possible to notify them that they should download the latest version from sourceforge, but someone has to do that

**Comment by cheusov** [comment]
Oh, my God! How could I miss to push tags :-O
Thanks a lot for notifying me!
